### ISSUE TITLE
WARN

### ISSUE THREAD

**Issue by CongYuSanXun** [BlossomMods/BlossomLib#14] opened 2023-10-05 02:13 UTC
When a player joins the server, an error will be reported. The error is as follows:

 [Netty Epoll Server IO #3/WARN]: Failed to load language resource at blossom:lang/zh_cn.json
com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Unterminated object at line 17 column 4 path $.blossom.homes.setMax.delimiter
        at com.google.gson.Gson.fromJson(Gson.java:1229) ~[gson-2.10.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:1124) ~[gson-2.10.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:1062) ~[gson-2.10.jar:?]
        at net.minecraft.util.Language.load(Language.java:83) ~[server-intermediary.jar:?]
        at xyz.nucleoid.server.translations.impl.language.LanguageReader.read(LanguageReader.java:19) ~[server_translations_api-2.0.0+1.20-cd5a7fd5446f00f7.jar:?]
        at xyz.nucleoid.server.translations.impl.language.LanguageReader.lambda$collectDataPackTranslations$1(LanguageReader.java:42) ~[server_translations_api-2.0.0+1.20-cd5a7fd5446f00f7.jar:?]
        at xyz.nucleoid.server.translations.impl.language.TranslationStore.tryLoad(TranslationStore.java:50) ~[server_translations_api-2.0.0+1.20-cd5a7fd5446f00f7.jar:?]
        at xyz.nucleoid.server.translations.impl.language.TranslationStore.get(TranslationStore.java:37) ~[server_translations_api-2.0.0+1.20-cd5a7fd5446f00f7.jar:?]
        at xyz.nucleoid.server.translations.impl.ServerTranslations.createLanguage(ServerTranslations.java:120) ~[server_translations_api-2.0.0+1.20-cd5a7fd5446f00f7.jar:?]
        at xyz.nucleoid.server.translations.impl.ServerTranslations.getLanguage(ServerTranslations.java:105) ~[server_translations_api-2.0.0+1.20-cd5a7fd5446f00f7.jar:?]
        at xyz.nucleoid.server.translations.impl.ServerTranslations.getLanguage(ServerTranslations.java:89) ~[server_translations_api-2.0.0+1.20-cd5a7fd5446f00f7.jar:?]
        at xyz.nucleoid.server.translations.api.LocalizationTarget.getLanguage(LocalizationTarget.java:21) ~[server_translations_api-2.0.0+1.20-cd5a7fd5446f00f7.jar:?]
        at xyz.nucleoid.server.translations.impl.nbt.StackNbtLocalizer.localize(StackNbtLocalizer.java:18) ~[server_translations_api-2.0.0+1.20-cd5a7fd5446f00f7.jar:?]
        at net.minecraft.network.PacketByteBuf.modify$gcj000$server_translations_api$stapi$writeItemStackTag(PacketByteBuf.java:3877) ~[server-intermediary.jar:?]
        at net.minecraft.network.PacketByteBuf.writeItemStack(PacketByteBuf.java:656) ~[server-intermediary.jar:?]
        at net.minecraft.network.PacketByteBuf.writeCollection(PacketByteBuf.java:226) ~[server-intermediary.jar:?]
        at net.minecraft.recipe.Ingredient.write(Ingredient.java:85) ~[server-intermediary.jar:?]
        at net.minecraft.recipe.ShapedRecipe$Serializer.write(ShapedRecipe.java:322) ~[server-intermediary.jar:?]
        at net.minecraft.recipe.ShapedRecipe$Serializer.write(ShapedRecipe.java:279) ~[server-intermediary.jar:?]
        at net.minecraft.network.packet.s2c.play.SynchronizeRecipesS2CPacket.writeRecipe(SynchronizeRecipesS2CPacket.java:52) ~[server-intermediary.jar:?]
        at net.minecraft.network.PacketByteBuf.writeCollection(PacketByteBuf.java:226) ~[server-intermediary.jar:?]
        at net.minecraft.network.packet.s2c.play.SynchronizeRecipesS2CPacket.write(SynchronizeRecipesS2CPacket.java:27) ~[server-intermediary.jar:?]
        at net.minecraft.network.PacketEncoder.encode(PacketEncoder.java:45) ~[server-intermediary.jar:?]
        at net.minecraft.network.PacketEncoder.encode(PacketEncoder.java:14) ~[server-intermediary.jar:?]
        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107) ~[netty-codec-4.1.82.Final.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[netty-transport-4.1.82.Final.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709) ~[netty-transport-4.1.82.Final.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792) ~[netty-transport-4.1.82.Final.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702) ~[netty-transport-4.1.82.Final.jar:?]
        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:113) ~[netty-codec-4.1.82.Final.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[netty-transport-4.1.82.Final.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764) ~[netty-transport-4.1.82.Final.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext$WriteTask.run(AbstractChannelHandlerContext.java:1071) ~[netty-transport-4.1.82.Final.jar:?]
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.82.Final.jar:?]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[netty-common-4.1.82.Final.jar:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[netty-common-4.1.82.Final.jar:?]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:403) ~[netty-transport-classes-epoll-4.1.82.Final.jar:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.82.Final.jar:?]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.82.Final.jar:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: com.google.gson.stream.MalformedJsonException: Unterminated object at line 17 column 4 path $.blossom.homes.setMax.delimiter
        at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1657) ~[gson-2.10.jar:?]
        at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:500) ~[gson-2.10.jar:?]
        at com.google.gson.stream.JsonReader.hasNext(JsonReader.java:422) ~[gson-2.10.jar:?]
        at com.google.gson.internal.bind.TypeAdapters$28.read(TypeAdapters.java:779) ~[gson-2.10.jar:?]
        at com.google.gson.internal.bind.TypeAdapters$28.read(TypeAdapters.java:725) ~[gson-2.10.jar:?]
        at com.google.gson.internal.bind.TypeAdapters$34$1.read(TypeAdapters.java:1007) ~[gson-2.10.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:1214) ~[gson-2.10.jar:?]
        ... 39 more

**Comment by CodedSakura** [comment] 2023-11-10 11:16
[the zh_cn locale file for BlossomHomes (line 16)](https://github.com/BlossomMods/BlossomHomes/blob/main/src/main/resources/data/blossom/lang/zh_cn.json#L16) is missing a comma at the end of the line.
as it's a low priority bug, i'll merge a fix next time i update BlossomHomes

**Comment by CodedSakura** [comment] 2024-05-06 08:35
duplicate of #15

**Closed by CodedSakura** 2024-05-06 08:35 UTC
Labels: bug
