### ISSUE TITLE
Changing startHomes in BlossomHomes.json doesnt update the maximum amount of homes in game.

### ISSUE THREAD

**Issue by Ketoro** [BlossomMods/BlossomLib#20] opened 2024-07-30 21:04 UTC
Changing maximum amount of homes in BlossomHomes.json doesnt actually update the maximum amount of homes in game.
![PXL_20240730_205917149](https://github.com/user-attachments/assets/aed48306-1e68-45c7-8cfa-aca2d8601811)
![Screenshot_20240730_140248](https://github.com/user-attachments/assets/8e54c62e-111d-4b7b-91f2-f886afbd0f65)

**Comment by Ketoro** [comment] 2024-07-30 21:08
also /sethome <name> gives an error about only being able to set the default amount of homes.
![image](https://github.com/user-attachments/assets/c5bc26f3-aa84-4d8e-a2eb-c2060188215b)

**Comment by CodedSakura** [comment] 2024-07-31 04:37
duplicate of https://github.com/BlossomMods/BlossomHomes/issues/18

**Closed by CodedSakura** 2024-07-31 04:37 UTC
